# Generated by Django 3.2.8 on 2021-12-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211225_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='images1',
            field=models.ImageField(default='a.jpeg', upload_to='products/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
