# Generated by Django 3.2.8 on 2022-01-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productcomment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='subject',
        ),
    ]
