# Generated by Django 3.2.8 on 2022-01-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_cart_item_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
