# Generated by Django 3.2.8 on 2022-01-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_product_id_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_size_id',
            new_name='product_size',
        ),
    ]
