# Generated by Django 3.2.8 on 2021-12-04 23:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title_image',
            field=models.ImageField(default=datetime.datetime(2021, 12, 4, 23, 41, 43, 905787, tzinfo=utc), upload_to='posts/%d/%m/%Y'),
            preserve_default=False,
        ),
    ]
