# Generated by Django 3.2.8 on 2021-12-07 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_postcomment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
